import { CalculatorItem, CalculatorCategory } from '../types/catalog.types';

export const SMARTCALC_CATEGORIES: { id: CalculatorCategory; name: string; icon: string; count: number }[] = [
  { id: '💰 Loans', name: 'Loans', icon: '💰', count: 4 },
  { id: '📈 Investments', name: 'Investments', icon: '📈', count: 5 },
  { id: '📊 Trading', name: 'Trading', icon: '📊', count: 4 },
  { id: '🏦 Banking', name: 'Banking', icon: '🏦', count: 4 },
  { id: '💵 Tax & Salary', name: 'Tax & Salary', icon: '💵', count: 3 },
  { id: '🚗 Vehicle', name: 'Vehicle', icon: '🚗', count: 3 },
  { id: '🏠 Home', name: 'Home', icon: '🏠', count: 2 },
  { id: '🏃 Health', name: 'Health', icon: '🏃', count: 3 },
  { id: '🎓 Student', name: 'Student', icon: '🎓', count: 2 },
  { id: '🧮 Math', name: 'Math', icon: '🧮', count: 6 },
  { id: '📅 Date & Time', name: 'Date & Time', icon: '📅', count: 2 },
  { id: '🔄 Converters', name: 'Converters', icon: '🔄', count: 1 },
];

export const calculatorToolCatalog: CalculatorItem[] = [
  // ==========================================
  // 1. 💰 Loans (4)
  // ==========================================
  {
    id: 'emi',
    name: 'EMI Calculator',
    title: 'EMI Calculator',
    shortDescription: 'Monthly loan installment with interest breakdown',
    description: 'Calculate equated monthly installments (EMI) for home, car, or personal loans with amortization schedules.',
    category: '💰 Loans',
    icon: '💳',
    route: 'EMICalculator',
    initialMode: 'general',
    popularity: 99,
    isPopular: true,
    status: 'available',
    keywords: ['emi', 'loan', 'installment', 'mortgage', 'borrow', 'interest', 'monthly'],
    aliases: ['loan emi', 'installment calculator'],
    disclaimer: 'Estimates based on standard monthly reducing balance formula. Actual bank terms may vary.',
  },
  {
    id: 'home_loan',
    name: 'Home Loan Calculator',
    title: 'Home Loan Calculator',
    shortDescription: 'Plan housing loan EMI & total interest payable',
    description: 'Calculate monthly home loan EMIs, total interest outlay, and full amortization schedule.',
    category: '💰 Loans',
    icon: '🏡',
    route: 'EMICalculator',
    initialMode: 'home',
    popularity: 92,
    isPopular: true,
    status: 'available',
    keywords: ['home loan', 'housing', 'property loan', 'mortgage', 'housing finance', 'emi'],
    aliases: ['mortgage calculator', 'house loan'],
    disclaimer: 'Excludes processing fees, insurance, and statutory stamp duty taxes.',
  },
  {
    id: 'car_loan',
    name: 'Car Loan Calculator',
    title: 'Car Loan Calculator',
    shortDescription: 'Automobile four-wheeler financing & down payment',
    description: 'Calculate vehicle auto financing installments, down payment balance, and total interest.',
    category: '💰 Loans',
    icon: '🚘',
    route: 'EMICalculator',
    initialMode: 'car',
    popularity: 84,
    status: 'available',
    keywords: ['car loan', 'auto loan', 'vehicle loan', 'four wheeler', 'auto finance', 'emi'],
    aliases: ['auto loan', 'vehicle emi'],
  },
  {
    id: 'loan_prepayment',
    name: 'Loan Prepayment Calculator',
    title: 'Loan Prepayment Calculator',
    shortDescription: 'Save interest & reduce tenure with prepayments',
    description: 'See how making lump-sum or periodic prepayments shortens your loan tenure and saves thousands in interest.',
    category: '💰 Loans',
    icon: '⚡',
    route: 'EMICalculator',
    initialMode: 'prepayment',
    popularity: 86,
    isPopular: true,
    status: 'available',
    keywords: ['prepayment', 'foreclosure', 'part payment', 'tenure reduction', 'interest saver', 'loan early payoff'],
    aliases: ['prepay calculator', 'early payoff'],
  },

  // ==========================================
  // 2. 📈 Investments (5)
  // ==========================================
  {
    id: 'sip',
    name: 'SIP Calculator',
    title: 'SIP Calculator',
    shortDescription: 'Monthly mutual fund compounding wealth generator',
    description: 'Simulate long-term wealth accumulation through monthly Systematic Investment Plans (SIP).',
    category: '📈 Investments',
    icon: '📈',
    route: 'SIPCalculator',
    initialMode: 'sip',
    popularity: 98,
    isPopular: true,
    status: 'available',
    keywords: ['sip', 'mutual fund', 'invest', 'wealth', 'compounding', 'monthly investment', 'equity'],
    aliases: ['systematic investment plan', 'mf sip'],
    disclaimer: 'Mutual fund investments are subject to market risks. Projected returns are illustrative.',
  },
  {
    id: 'lumpsum',
    name: 'Lumpsum Calculator',
    title: 'Lumpsum Calculator',
    shortDescription: 'One-time investment maturity & compound growth',
    description: 'Calculate the future maturity value of a one-time lump sum mutual fund or equity deposit.',
    category: '📈 Investments',
    icon: '💰',
    route: 'SIPCalculator',
    initialMode: 'lumpsum',
    popularity: 88,
    status: 'available',
    keywords: ['lumpsum', 'one time investment', 'compound interest', 'growth', 'wealth multiplier'],
    aliases: ['compound interest calculator', 'single deposit'],
  },
  {
    id: 'swp',
    name: 'SWP Calculator',
    title: 'SWP Calculator',
    shortDescription: 'Systematic withdrawal for regular monthly income',
    description: 'Plan regular monthly income and retirement pension withdrawals from your mutual fund corpus.',
    category: '📈 Investments',
    icon: '💸',
    route: 'SIPCalculator',
    initialMode: 'swp',
    popularity: 80,
    status: 'available',
    keywords: ['swp', 'systematic withdrawal', 'regular income', 'pension', 'cashflow', 'retirement payout'],
    aliases: ['systematic withdrawal plan', 'pension cashflow'],
  },
  {
    id: 'goal_planner',
    name: 'Goal SIP Planner',
    title: 'Goal SIP Planner',
    shortDescription: 'Target wealth & monthly SIP required',
    description: 'Determine the exact monthly investment required to reach your target savings milestone in time.',
    category: '📈 Investments',
    icon: '🎯',
    route: 'SIPCalculator',
    initialMode: 'goal',
    popularity: 83,
    status: 'available',
    keywords: ['goal', 'target wealth', 'retirement target', 'crorepati', 'savings target', 'future goal'],
    aliases: ['target wealth planner', 'goal calculator'],
  },
  {
    id: 'cagr',
    name: 'CAGR Calculator',
    title: 'CAGR Calculator',
    shortDescription: 'Compound Annual Growth Rate of investments',
    description: 'Measure the annual compounded return rate of any multi-year financial investment accurately.',
    category: '📈 Investments',
    icon: '📊',
    route: 'SIPCalculator',
    initialMode: 'cagr',
    popularity: 82,
    status: 'available',
    keywords: ['cagr', 'growth rate', 'annual return', 'compounded return', 'investment performance'],
    aliases: ['compound annual growth rate', 'annual return calculator'],
  },

  // ==========================================
  // 3. 📊 Trading (4)
  // ==========================================
  {
    id: 'stock_pnl',
    name: 'Stock P&L Calculator',
    title: 'Stock P&L Calculator',
    shortDescription: 'Net profit/loss with brokerage & statutory charges',
    description: 'Calculate net realized profit or loss on stock trades after deducting brokerage, STT, exchange, and GST charges.',
    category: '📊 Trading',
    icon: '📉',
    route: 'StockProfitCalculator',
    initialMode: 'pnl',
    popularity: 94,
    isPopular: true,
    status: 'available',
    keywords: ['stock pnl', 'profit loss', 'brokerage', 'stt', 'trading profit', 'delivery', 'intraday', 'charges'],
    aliases: ['stock profit', 'brokerage calculator'],
    disclaimer: 'Standard regulatory charges (STT, GST, SEBI turnover) are calculated per SEBI/Exchange rules.',
  },
  {
    id: 'stock_average',
    name: 'Stock Average Down Calculator',
    title: 'Stock Average Down Calculator',
    shortDescription: 'Blended price after buying at lower levels',
    description: 'Determine your new weighted average share purchase price when buying additional shares on market dips.',
    category: '📊 Trading',
    icon: '⚖️',
    route: 'StockProfitCalculator',
    initialMode: 'average',
    popularity: 85,
    status: 'available',
    keywords: ['stock average', 'average down', 'blended price', 'buy dip', 'holding cost'],
    aliases: ['average down calculator', 'share average'],
  },
  {
    id: 'stock_target',
    name: 'Target & Break-Even Calculator',
    title: 'Target & Break-Even Calculator',
    shortDescription: 'Required exit price to reach target return',
    description: 'Calculate the exact selling price needed to achieve your desired net profit % or break-even after charges.',
    category: '📊 Trading',
    icon: '🎯',
    route: 'StockProfitCalculator',
    initialMode: 'target',
    popularity: 79,
    status: 'available',
    keywords: ['target price', 'break even', 'exit price', 'trading target', 'profit goal'],
    aliases: ['break even calculator', 'target price'],
  },
  {
    id: 'position_size',
    name: 'Position Size & Stop-Loss',
    title: 'Position Size & Stop-Loss',
    shortDescription: 'Risk management & optimal quantity to buy',
    description: 'Calculate the maximum number of shares to buy based on your portfolio capital risk limit and stop-loss level.',
    category: '📊 Trading',
    icon: '🛡️',
    route: 'StockProfitCalculator',
    initialMode: 'sl_sizing',
    popularity: 81,
    status: 'available',
    keywords: ['position size', 'stop loss', 'risk management', 'capital risk', 'trading quantity', 'risk per trade'],
    aliases: ['position sizing', 'stop loss calculator'],
  },

  // ==========================================
  // 4. 🏦 Banking (4)
  // ==========================================
  {
    id: 'fd_calculator',
    name: 'Fixed Deposit (FD) Calculator',
    title: 'Fixed Deposit (FD) Calculator',
    shortDescription: 'Bank term deposit maturity & compound interest',
    description: 'Calculate maturity payout and interest earned on cumulative bank fixed deposits with quarterly compounding.',
    category: '🏦 Banking',
    icon: '🏦',
    route: 'BankingCalculator',
    initialMode: 'fd',
    popularity: 93,
    isPopular: true,
    status: 'available',
    keywords: ['fd', 'fixed deposit', 'term deposit', 'bank interest', 'quarterly compounding', 'maturity'],
    aliases: ['fd calculator', 'term deposit'],
  },
  {
    id: 'rd_calculator',
    name: 'Recurring Deposit (RD) Calculator',
    title: 'Recurring Deposit (RD) Calculator',
    shortDescription: 'Monthly bank recurring deposit maturity',
    description: 'Calculate total maturity amount and cumulative interest earned on regular monthly bank RD installments.',
    category: '🏦 Banking',
    icon: '🔄',
    route: 'BankingCalculator',
    initialMode: 'rd',
    popularity: 87,
    status: 'available',
    keywords: ['rd', 'recurring deposit', 'monthly deposit', 'bank savings', 'rd maturity'],
    aliases: ['rd calculator', 'recurring deposit'],
  },
  {
    id: 'fd_interest',
    name: 'FD Payout Calculator',
    title: 'FD Payout Calculator',
    shortDescription: 'Monthly & quarterly non-cumulative interest payout',
    description: 'Calculate regular income payouts from non-cumulative fixed deposits for retirees and monthly budgeters.',
    category: '🏦 Banking',
    icon: '💵',
    route: 'BankingCalculator',
    initialMode: 'fd_payout',
    popularity: 78,
    status: 'available',
    keywords: ['fd payout', 'monthly interest', 'quarterly interest', 'senior citizen fd', 'non cumulative fd'],
    aliases: ['fd monthly payout', 'regular interest'],
  },
  {
    id: 'gratuity',
    name: 'Gratuity Calculator',
    title: 'Gratuity Calculator',
    shortDescription: 'Statutory gratuity benefit payout on exit',
    description: 'Calculate your statutory gratuity payout entitlement based on completed years of service and final salary.',
    category: '🏦 Banking',
    icon: '🎁',
    route: 'BankingCalculator',
    initialMode: 'gratuity',
    popularity: 80,
    status: 'available',
    keywords: ['gratuity', 'retirement benefit', 'gratuity act', 'job exit payout', 'statutory benefit'],
    aliases: ['gratuity calculator', 'exit benefit'],
  },

  // ==========================================
  // 5. 💵 Tax & Salary (3)
  // ==========================================
  {
    id: 'income_tax',
    name: 'Income Tax Calculator',
    title: 'Income Tax Calculator',
    shortDescription: 'Old vs New Regime side-by-side comparison',
    description: 'Compare tax liability under the Old Regime and New Tax Regime (Budget 2024 slabs) to see which saves more.',
    category: '💵 Tax & Salary',
    icon: '🏛️',
    route: 'TaxSalaryCalculator',
    initialMode: 'income_tax',
    popularity: 97,
    isPopular: true,
    status: 'available',
    keywords: ['income tax', 'old regime', 'new regime', 'tax comparison', 'tax slabs', 'cess', 'rebate 87a'],
    aliases: ['income tax calculator', 'tax slab comparison'],
    disclaimer: 'Calculations are estimates based on declared tax slabs. Consult a Chartered Accountant for filings.',
  },
  {
    id: 'inhand_salary',
    name: 'In-Hand Salary Calculator',
    title: 'In-Hand Salary Calculator',
    shortDescription: 'Annual CTC to monthly take-home salary',
    description: 'Convert annual CTC into monthly in-hand net salary after Employee PF, Professional Tax, and Income Tax deductions.',
    category: '💵 Tax & Salary',
    icon: '💵',
    route: 'TaxSalaryCalculator',
    initialMode: 'inhand',
    popularity: 91,
    isPopular: true,
    status: 'available',
    keywords: ['in hand salary', 'take home', 'ctc to in hand', 'monthly salary', 'pf deduction', 'professional tax'],
    aliases: ['take home salary', 'ctc calculator'],
  },
  {
    id: 'gst',
    name: 'GST Calculator',
    title: 'GST Calculator',
    shortDescription: 'Add or remove GST (3%, 5%, 12%, 18%, 28%)',
    description: 'Instantly calculate net amount, GST amount, and gross total for inclusive and exclusive GST rates.',
    category: '💵 Tax & Salary',
    icon: '%',
    route: 'GSTCalculator',
    popularity: 96,
    isPopular: true,
    status: 'available',
    keywords: ['gst', 'goods and services tax', 'gst inclusive', 'gst exclusive', 'tax invoice', 'cgst', 'sgst'],
    aliases: ['gst calculator', 'sales tax'],
  },

  // ==========================================
  // 6. 🚗 Vehicle (3)
  // ==========================================
  {
    id: 'fuel_cost',
    name: 'Fuel Cost Calculator',
    title: 'Fuel Cost Calculator',
    shortDescription: 'Trip fuel expense & cost per passenger',
    description: 'Calculate fuel cost for any car or bike journey and split expenses evenly among co-travelers.',
    category: '🚗 Vehicle',
    icon: '⛽',
    route: 'FuelCostCalculator',
    initialMode: 'fuel',
    popularity: 89,
    isPopular: true,
    status: 'available',
    keywords: ['fuel cost', 'petrol cost', 'diesel cost', 'trip cost', 'carpool split', 'fuel expense'],
    aliases: ['petrol calculator', 'trip fuel cost'],
  },
  {
    id: 'mileage_calc',
    name: 'Mileage Calculator',
    title: 'Mileage Calculator',
    shortDescription: 'Tank-to-tank vehicle fuel efficiency (km/L)',
    description: 'Calculate precise real-world fuel economy and efficiency using odometer reading and liters refueled.',
    category: '🚗 Vehicle',
    icon: '🚗',
    route: 'FuelCostCalculator',
    initialMode: 'mileage',
    popularity: 84,
    status: 'available',
    keywords: ['mileage', 'fuel efficiency', 'kmpl', 'tank to tank', 'fuel average', 'consumption'],
    aliases: ['fuel mileage', 'km per liter'],
  },
  {
    id: 'ev_charging',
    name: 'EV vs Fuel Calculator',
    title: 'EV vs Fuel Calculator',
    shortDescription: 'Electric vehicle charging cost vs petrol savings',
    description: 'Compare EV electricity charging expense against petrol/diesel running costs to evaluate monthly savings.',
    category: '🚗 Vehicle',
    icon: '⚡',
    route: 'FuelCostCalculator',
    initialMode: 'ev',
    popularity: 82,
    status: 'available',
    keywords: ['ev charging', 'electric vehicle', 'petrol vs ev', 'battery charging cost', 'green mobility', 'ev savings'],
    aliases: ['ev cost calculator', 'electric vehicle savings'],
  },

  // ==========================================
  // 7. 🏠 Home (2)
  // ==========================================
  {
    id: 'electricity_bill',
    name: 'Electricity Bill Calculator',
    title: 'Electricity Bill Calculator',
    shortDescription: 'Slab-wise electricity tariff & bill estimator',
    description: 'Estimate your monthly electricity power bill based on consumed units (kWh) and progressive tariff slabs.',
    category: '🏠 Home',
    icon: '💡',
    route: 'ElectricityCalculator',
    initialMode: 'bill',
    popularity: 91,
    isPopular: true,
    status: 'available',
    keywords: ['electricity bill', 'power bill', 'kwh', 'units consumed', 'slab rate', 'energy cost'],
    aliases: ['power bill calculator', 'electric bill'],
  },
  {
    id: 'solar_rooftop',
    name: 'Solar Rooftop Calculator',
    title: 'Solar Rooftop Calculator',
    shortDescription: 'Rooftop solar panel capacity & bill savings',
    description: 'Estimate required solar panel kW capacity, daily units generated, and lifetime electricity savings.',
    category: '🏠 Home',
    icon: '☀️',
    route: 'ElectricityCalculator',
    initialMode: 'solar',
    popularity: 80,
    status: 'available',
    keywords: ['solar rooftop', 'solar panels', 'clean energy', 'solar kw', 'inverter backup', 'electricity savings'],
    aliases: ['solar panel calculator', 'solar savings'],
  },

  // ==========================================
  // 8. 🏃 Health (3)
  // ==========================================
  {
    id: 'bmi',
    name: 'BMI & Ideal Weight',
    title: 'BMI & Ideal Weight',
    shortDescription: 'Body Mass Index & healthy weight range',
    description: 'Calculate your Body Mass Index (BMI) using WHO thresholds and discover your ideal healthy weight target.',
    category: '🏃 Health',
    icon: '⚖️',
    route: 'BMICalculator',
    initialMode: 'bmi',
    popularity: 95,
    isPopular: true,
    status: 'available',
    keywords: ['bmi', 'body mass index', 'ideal weight', 'obesity', 'fitness', 'healthy weight', 'underweight'],
    aliases: ['bmi calculator', 'ideal weight calculator'],
    disclaimer: 'BMI is a statistical screening measure and does not directly measure body fat percentage or muscle mass.',
  },
  {
    id: 'calorie',
    name: 'Calorie & TDEE Calculator',
    title: 'Calorie & TDEE Calculator',
    shortDescription: 'Daily maintenance calories & macro goals',
    description: 'Calculate Basal Metabolic Rate (BMR) and Total Daily Energy Expenditure (TDEE) to plan weight loss or gain.',
    category: '🏃 Health',
    icon: '🔥',
    route: 'BMICalculator',
    initialMode: 'calorie',
    popularity: 88,
    status: 'available',
    keywords: ['calorie', 'tdee', 'bmr', 'daily calories', 'weight loss', 'deficit', 'surplus', 'nutrition'],
    aliases: ['tdee calculator', 'calorie calculator'],
  },
  {
    id: 'water',
    name: 'Daily Hydration Calculator',
    title: 'Daily Hydration Calculator',
    shortDescription: 'Recommended daily water intake by body weight',
    description: 'Calculate your optimal daily water consumption in liters and glasses based on weight and activity level.',
    category: '🏃 Health',
    icon: '💧',
    route: 'BMICalculator',
    initialMode: 'water',
    popularity: 82,
    status: 'available',
    keywords: ['water intake', 'hydration', 'glasses of water', 'daily water', 'fluid requirement', 'health'],
    aliases: ['water calculator', 'hydration tracker'],
  },

  // ==========================================
  // 9. 🎓 Student (2)
  // ==========================================
  {
    id: 'attendance',
    name: 'Attendance Planner',
    title: 'Attendance Planner',
    shortDescription: 'Classes to attend or bunk to maintain target %',
    description: 'Calculate how many upcoming lectures you need to attend or can safely bunk while keeping above 75% or 80%.',
    category: '🎓 Student',
    icon: '📚',
    route: 'StudentCalculator',
    initialMode: 'attendance',
    popularity: 93,
    isPopular: true,
    status: 'available',
    keywords: ['attendance', 'bunk planner', '75 percent', 'college attendance', 'lecture bunker', 'attendance tracker'],
    aliases: ['bunk calculator', 'attendance manager'],
  },
  {
    id: 'cgpa',
    name: 'CGPA & SGPA Calculator',
    title: 'CGPA & SGPA Calculator',
    shortDescription: 'Convert CGPA to percentage & calculate semester GPA',
    description: 'Convert 10-point CGPA to percentage (CBSE, AICTE, Mumbai Univ) and compute weighted semester SGPA.',
    category: '🎓 Student',
    icon: '🎓',
    route: 'StudentCalculator',
    initialMode: 'cgpa',
    popularity: 90,
    status: 'available',
    keywords: ['cgpa', 'sgpa', 'gpa', 'grade point', 'cgpa to percentage', 'semester grades', 'college marks'],
    aliases: ['cgpa to percentage', 'gpa calculator'],
  },

  // ==========================================
  // 10. 🧮 Math (1 unified hub + supporting screens)
  // ==========================================
  {
    id: 'math_hub',
    name: 'Math Hub',
    title: 'Math Hub - All Calculators & Tools',
    shortDescription: 'Unified hub for all math calculators & utilities',
    description: 'Access basic calculator, scientific calculator, and all specialized math tools from one screen.',
    category: '🧮 Math',
    icon: '➗',
    route: 'UnifiedMath',
    popularity: 100,
    isPopular: true,
    status: 'available',
    keywords: ['math', 'calculator', 'basic', 'scientific', 'tools', 'percentage', 'lcm', 'hcf', 'prime', 'fraction'],
    aliases: ['math calculator', 'all math tools'],
  },
  {
    id: 'basic_calc',
    name: 'Basic Calculator',
    title: 'Basic Calculator',
    shortDescription: 'Everyday standard arithmetic & memory calculator',
    description: 'Clean, responsive standard calculator with percent calculations, undo/redo, and memory recall.',
    category: '🧮 Math',
    icon: '➗',
    route: 'BasicCalculator',
    popularity: 100,
    isPopular: true,
    status: 'available',
    keywords: ['calculator', 'basic', 'math', 'arithmetic', 'add', 'subtract', 'multiply', 'divide', 'percent'],
    aliases: ['standard calculator', 'simple calculator'],
  },
  {
    id: 'scientific_calc',
    name: 'Scientific Calculator',
    title: 'Scientific Calculator',
    shortDescription: 'Trigonometry, logarithms, powers & constants',
    description: 'Advanced engineering and math calculator supporting sin, cos, tan, log, ln, sqrt, powers, DEG and RAD.',
    category: '🧮 Math',
    icon: '🔬',
    route: 'ScientificCalculator',
    popularity: 87,
    status: 'available',
    keywords: ['scientific', 'trig', 'log', 'sin', 'cos', 'tan', 'engineering', 'powers', 'roots', 'radian'],
    aliases: ['scientific calculator', 'engineering calculator'],
  },
  {
    id: 'percentage',
    name: 'Percentage & Discount',
    title: 'Percentage & Discount',
    shortDescription: 'Percentage change, percentage of, and price discount',
    description: 'Compute percentage increase, decrease, percentage of values, and multi-step promotional discounts.',
    category: '🧮 Math',
    icon: '🏷️',
    route: 'PercentageCalculator',
    popularity: 94,
    isPopular: true,
    status: 'available',
    keywords: ['percentage', 'discount', 'percent of', 'percent change', 'percent hike', 'price reduction', 'margin'],
    aliases: ['percentage calculator', 'discount calculator'],
  },
  {
    id: 'math_tools',
    name: 'Math Tools & Number Theory',
    title: 'Math Tools (LCM, HCF, Primes)',
    shortDescription: 'LCM, HCF, factors, primes, fractions & random numbers',
    description: 'Comprehensive math utility covering LCM, HCF/GCD, prime factorization, fractions, ratios, and probability.',
    category: '🧮 Math',
    icon: '🎲',
    route: 'MathToolsCalculator',
    initialMode: 'lcm_hcf',
    popularity: 88,
    isPopular: true,
    status: 'available',
    keywords: ['lcm', 'hcf', 'gcd', 'prime', 'factors', 'fraction', 'ratio', 'probability', 'random', 'average'],
    aliases: ['lcm calculator', 'hcf calculator', 'fraction calculator', 'prime checker'],
  },
  {
    id: 'advanced_math',
    name: 'Algebra & Equations',
    title: 'Algebra Solver (Quadratic & Roots)',
    shortDescription: 'Solve quadratic equations, nth roots & logarithms',
    description: 'Advanced equation solver supporting quadratic polynomials with step-by-step discriminant and roots.',
    category: '🧮 Math',
    icon: '📐',
    route: 'AdvancedMathCalculator',
    initialMode: 'quadratic',
    popularity: 85,
    status: 'available',
    keywords: ['algebra', 'quadratic', 'equation solver', 'roots', 'logarithm', 'powers', 'polynomial'],
    aliases: ['quadratic equation solver', 'algebra calculator', 'root calculator'],
  },

  // ==========================================
  // 11. 📅 Date & Time (2)
  // ==========================================
  {
    id: 'age',
    name: 'Age Calculator',
    title: 'Age Calculator',
    shortDescription: 'Exact chronological age & next birthday countdown',
    description: 'Find your precise age in years, months, days, total hours, and get a countdown to your next birthday.',
    category: '📅 Date & Time',
    icon: '🎂',
    route: 'AgeCalculator',
    initialMode: 'age',
    popularity: 95,
    isPopular: true,
    status: 'available',
    keywords: ['age', 'birth date', 'birthday', 'chronological age', 'days lived', 'age in months'],
    aliases: ['birthday calculator', 'chronological age'],
  },
  {
    id: 'date_diff',
    name: 'Date Difference Calculator',
    title: 'Date Difference Calculator',
    shortDescription: 'Days, weeks & business working days between dates',
    description: 'Calculate exact duration between two calendar dates, with optional weekend exclusion for working days.',
    category: '📅 Date & Time',
    icon: '📅',
    route: 'AgeCalculator',
    initialMode: 'date_diff',
    popularity: 83,
    status: 'available',
    keywords: ['date difference', 'days between', 'duration', 'working days', 'business days', 'calendar count'],
    aliases: ['days calculator', 'business days'],
  },

  // ==========================================
  // 12. 🔄 Converters (1)
  // ==========================================
  {
    id: 'unit_converter',
    name: 'All-in-One Unit Converter',
    title: 'All-in-One Unit Converter',
    shortDescription: 'Length, weight, temperature, speed, area & volume',
    description: 'Convert between metric and imperial units across 7 physical categories with real-time conversion.',
    category: '🔄 Converters',
    icon: '🔄',
    route: 'UnitConverter',
    popularity: 96,
    isPopular: true,
    status: 'available',
    keywords: ['unit converter', 'metric', 'imperial', 'length', 'weight', 'temperature', 'speed', 'area', 'volume', 'data'],
    aliases: ['measurement converter', 'units'],
  },
];
